using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace NiVE3.SourceGenerator.LanguageResourceGenerator
{
    static class LanguageResourceKeyEmitter
    {
        static readonly string Namespace = typeof(LanguageResourceGenerator).Namespace;

        static readonly string HasLanguageKeyFullName = $"{Namespace}.HasLanguageKeyAttribute";

        static readonly string LanguageKeyFullName = $"{Namespace}.LanguageKeyAttribute";

        public static void RegisterAttributes(IncrementalGeneratorPostInitializationContext context)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            context.AddSource("HasLanguageKeyAttribute", $"namespace {Namespace};" + """

using System;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
sealed class HasLanguageKeyAttribute : Attribute { }
""");

            context.CancellationToken.ThrowIfCancellationRequested();

            context.AddSource("LanguageKeyAttribute", $"namespace {Namespace};" + """

using System;

[AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
sealed class LanguageKeyAttribute : Attribute { }
""");
        }

        public static void RegisterEmit(IncrementalGeneratorInitializationContext context)
        {
            var typeDefinitions = context.SyntaxProvider.ForAttributeWithMetadataName(
                HasLanguageKeyFullName,
                static (node, token) => node is ClassDeclarationSyntax,
                static (context, token) => (TypeDeclarationSyntax)context.TargetNode
            );

            var source = typeDefinitions.Combine(context.CompilationProvider).WithComparer(Comparer.Instance);

            context.RegisterSourceOutput(source, (context, source) =>
            {
                context.CancellationToken.ThrowIfCancellationRequested();

                Emit(context, source.Item1, source.Item2);
            });
        }

        static void Emit(SourceProductionContext context, TypeDeclarationSyntax syntax, Compilation compilation)
        {
            var semanticModel = compilation.GetSemanticModel(syntax.SyntaxTree);
            if (semanticModel == null)
            {
                return;
            }

            context.CancellationToken.ThrowIfCancellationRequested();

            if (semanticModel.GetDeclaredSymbol(syntax, context.CancellationToken) is not INamedTypeSymbol typeSymbol)
            {
                return;
            }

            context.CancellationToken.ThrowIfCancellationRequested();

            var hasLanguageKeySymbol = EmitterUtil.GetTypeSymbol(compilation, HasLanguageKeyFullName);
            var languageKeySymbol = EmitterUtil.GetTypeSymbol(compilation, LanguageKeyFullName);

            context.CancellationToken.ThrowIfCancellationRequested();

            // クラスに適用されているかのチェックのみ実行
            EmitterUtil.GetAttributeData(typeSymbol, hasLanguageKeySymbol);

            context.CancellationToken.ThrowIfCancellationRequested();

            if (!Validate(context, syntax, typeSymbol))
            {
                return;
            }

            context.CancellationToken.ThrowIfCancellationRequested();

            var fileName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "")
                .Replace("<", "_")
                .Replace(">", "_") + ".LanguageResourceKeyGenerator.g.cs";

            var code = new StringBuilder($$"""
// <auto-generated/>
#nullable enable
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604

using System;
using System.Windows;
using NiVE3.Plugin.Resource;

namespace {{typeSymbol.ContainingNamespace}};

partial class {{typeSymbol.Name}}
{
    public class ResourceKeys
    {
""");
            code.AppendLine();

            var fields = typeSymbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f is { IsStatic: true, DeclaredAccessibility: Accessibility.Public, IsImplicitlyDeclared: false, CanBeReferencedByName: true })
                .Where(f => f.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, languageKeySymbol)))
                .ToArray();
            foreach (var field in fields)
            {
                code.AppendLine($"        public static readonly LanguageResourceKey {field.Name} = new LanguageResourceKey(typeof({typeSymbol.Name}), {typeSymbol.Name}.{field.Name});");
            }

            code.AppendLine("""
    }
}
""");

            context.AddSource(fileName, code.ToString());
        }

        static bool Validate(SourceProductionContext context, TypeDeclarationSyntax syntax, INamedTypeSymbol typeSymbol)
        {
            if (!syntax.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(HasLanguageKeyDiagnosticDescriptors.MustBePartial, syntax.Identifier.GetLocation(), typeSymbol.Name)
                );
                return false;
            }

            var baseType = typeSymbol.BaseType;
            while (baseType != null)
            {
                if (baseType.ToString() == "System.Windows.ResourceDictionary")
                {
                    break;
                }
                baseType = baseType.BaseType;
                if (baseType == null)
                {
                    context.ReportDiagnostic(
                        Diagnostic.Create(HasLanguageKeyDiagnosticDescriptors.TypeIsNotResourceDictionary, syntax.Identifier.GetLocation(), typeSymbol.Name)
                    );
                    return false;
                }
            }

            return true;
        }
    }
}
